name: telegram feedback bot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: telegram-feedback-bot:latest
