name: Greeting from Akseli

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build project docker image
        run: |
          docker compose build -f docker-compose.yml
