name: ci

on:
  push:
    branches:
      - "dockerize"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: Whree
        with:
          context: .
          file: ./Dockerfile
          push: false
