name: Greeting from Akseli

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build project docker image
        uses: AS-kilta/telegram-feedback-bot
        with:
          context: .
          file: ./Dockerfile
          push: false
